[package]
name = "app_launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.8.1"
rand = "0.8.5"
shellexpand = "3.1.0"
